services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.10.0@sha256:e9279e580bb25c512cf6e54c36e215a5cbd2881d1f201cf2a8213a97b14be3d2
    container_name: zigbee2mqtt
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyACM0
    volumes:
      - /run/udev:/run/udev:ro
      - type: volume
        source: nfs
        target: /app/data
        volume:
          nocopy: true
volumes:
  nfs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.4,nolock,soft,rw"
      device: ":/nfs/zigbee2mqtt"
