name: renovate
permissions: write-all
on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v40.3.2
      with:
        configurationFile: .github/renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}

